### ISSUE TITLE
YAML support

### ISSUE THREAD

**Issue by josephfarina** [felixmosh/i18next-hmr#20] opened 2020-10-05 19:43 UTC
Hey thanks for creating this package 😄. I was wondering if YAML is supported? When I make changes to the locale file I receive the error I pasted below in the dev console. But when I hard refresh the translations are updated correctly.

```
[I18NextHMR] failed parsing /static/locales/en-US/common.yml to json
overrideMethod @ react_devtools_backend.js:2273
log @ client-hmr.js?e903:6
eval @ client-hmr.js?e903:31
eval @ i18next.js?5f34:1985
eval @ i18next.js?5f34:1558
loaded @ i18next.js?5f34:1540
eval @ i18next.js?5f34:1640
eval @ i18next.js?5f34:1586
eval @ index.js?ac22:132
eval @ request.js?ad38:82
Promise.then (async)
eval @ request.js?ad38:81
Promise.then (async)
requestWithFetch @ request.js?ad38:77
request @ request.js?ad38:155
loadUrl @ index.js?ac22:115
read @ index.js?ac22:108
read @ i18next.js?5f34:1578
loadOne @ i18next.js?5f34:1636
eval @ i18next.js?5f34:1612
prepareLoading @ i18next.js?5f34:1611
reload @ i18next.js?5f34:1623
reloadResources @ i18next.js?5f34:1983
reloadTranslations @ client-hmr.js?e903:29
eval @ client-hmr.js?e903:58
hotApplyInternal @ webpack.js?ts=1601926766807:724
hotApply @ webpack.js?ts=1601926766807:412
(anonymous) @ webpack.js?ts=1601926766807:387
Promise.then (async)
hotUpdateDownloaded @ webpack.js?ts=1601926766807:386
hotAddUpdateChunk @ webpack.js?ts=1601926766807:362
webpackHotUpdateCallback @ webpack.js?ts=1601926766807:58
(anonymous) @ challenges.93cf4c032a0568502ef2.hot-update.js:1
```

**Comment by felixmosh** [comment] 2020-10-05 20:24
Hi, thank you for reporting this issue 🙏🏼 

I wasn’t aware about the ability to use yml files as translations.
Can you give some more details? A reproduction repo should be helpful.

**Comment by felixmosh** [comment] 2020-10-06 09:13
From your stack trace looks like the error is comes from i18next, this may imply that the problem is in your config.

Can you add your i18next config?

**Comment by felixmosh** [comment] 2020-10-08 09:14
Ping? :]

**Comment by josephfarina** [comment] 2020-10-08 16:38
Hey @felixmosh sorry :) Wanted to setup a repo that reproduces the error but haven't had time yet. I will try and send one over today!

Here is my i18n config.

```javascript
const nextI18Next = new NextI18Next({
  defaultLanguage: 'en-US',
  otherLanguages: ['de-DE'],
  localeSubpaths: { 'de-DE': 'de-de' },
  localePath: path.resolve("./public/static/locales"),
  localeExtension: "yml",
  saveMissing: true,
  compatibilityJSON: "v4",
  fallbackLng: 'en-US',
  use: [require("i18next-icu")],
});

if (process.env.NODE_ENV !== "production") {
  if (process.browser) {
    // eslint-disable-next-line global-require
    const { applyClientHMR } = require("i18next-hmr/client");
    applyClientHMR(nextI18Next.i18n);
  } else {
    // eslint-disable-next-line global-require
    const { applyServerHMR } = require("i18next-hmr/server");
    applyServerHMR(nextI18Next.i18n);
  }
}
````

**Comment by felixmosh** [comment] 2020-10-08 17:06
I've investigated a bit regarding using `yaml` with i18next, by default it doesn't supports yaml, you need to provide it a parser.
From your config I don't see anything regarding it (changing the extension won't change the parser).

You can use [this example](https://github.com/felixmosh/i18next-hmr/tree/master/examples/next-with-next-i18next-without-custom-server) as your template for a reproducing repo.

**Comment by felixmosh** [comment] 2020-10-08 21:27
Ok, I've managed to reproduce the issue.

I18next supports `yaml` but `i18next-http-backend` (the plugin which fetches missing translations) doesn't.
All you need to do is specify `backend.parse` field, unfortunately `next-i18next` overrides the `backend` field :| https://github.com/isaachinman/next-i18next/issues/257#issuecomment-705831315

```javascript
const yaml = require('js-yaml');

const nextI18Next = new NextI18Next({
  otherLanguages: ['de'],
  localeSubpaths,
  localePath: path.resolve('./public/static/locales'),
  localeExtension: 'yaml',
  compatibilityJSON: 'v4',
  backend: {
    parse: function (data) {
      return yaml.load(data); // <-- tells to i18next-http-backend to parse the loaded file as yaml
    },
  },
});
```
```

**Comment by felixmosh** [comment] 2020-10-13 08:06
@josephfarina did it solved the issue for you?

**Comment by josephfarina** [comment] 2020-10-13 14:47
Hey @felixmosh thanks for the help on that solution! It solved the issue relating to `yml`, but it still doesn't quite work — not sure if it is related to this issue anymore.

That fix got rid of the `failed parsing` error. The translation xhr requests are now being made successfully. But the text still doesn't update until the page is refreshed. And also the translations under the `__NEXT_DATA__` id are never swapped out for the new ones.

Another bug it introduced is that after refreshing I keep getting errors like below. Which i'm wondering is related to the `process.browser` check? 🤔 


```
react-dom.development.js?61bb:88 Warning: Text content did not match. Server: "<Old Text>" Client: "<New Text>"
    in span (at Navbar.tsx:100)
    in a (at Link.tsx:35)
    in ForwardRef(Link) (at Navbar.tsx:93)
    in nav (at Navbar.tsx:92)
    in Navbar (at _app.tsx:38)
    in Provider (at _app.tsx:29)
    in AuthProvider (at _app.tsx:28)
    in Providers (at _app.tsx:37)
    in MyApp (created by withI18nextSSR(MyApp))
    in withI18nextSSR(MyApp) (created by AppWithTranslation)
    in NextStaticProvider (created by withI18nextTranslation(NextStaticProvider))
    in withI18nextTranslation(NextStaticProvider) (created by AppWithTranslation)
    in I18nextProvider (created by AppWithTranslation)
    in AppWithTranslation (created by withRouter(AppWithTranslation))
    in withRouter(AppWithTranslation)
    in ErrorBoundary (created by ReactDevOverlay)
    in ReactDevOverlay (created by Container)
    in Container (created by AppContainer)
    in AppContainer
    in Root
```

**Comment by felixmosh** [comment] 2020-10-13 15:06
The check for `process.browser` is a way to "override" only the backend field for the client, since `next-i18next` [doesn't allow to provide only one field of the backend](https://github.com/isaachinman/next-i18next/issues/848).
Looks like your server & client gets out of sync.

In my example with Yaml all worked fine, server & client.

**Comment by felixmosh** [comment] 2020-10-24 12:42
Since the original issue was resolved (with `parse` property) 
I'm closing this one, if you have different issue pls open a new issue.

**Closed by felixmosh** 2020-10-24 12:42 UTC
