### ISSUE TITLE
Client-HMR not working for getStaticPages in NextJS

### ISSUE THREAD

**Issue by skmohammadi** [felixmosh/i18next-hmr#109] opened 2022-05-23 13:26 UTC
**Describe the bug**
Client-HMR does not update resource that required in [SSG](https://nextjs.org/docs/basic-features/pages) page but not loaded by default in the I18N configuration.

**To Reproduce**

1. Install these two dependencies:
```
yarn add i18next-hmr i18next-http-backend --dev
```

2. Update the **next.config.js** like so:
```js
const { resolve } = require("path")
const { I18NextHMRPlugin } = require("i18next-hmr/plugin")

const localesDir = resolve("public/locales")

module.exports = {
  // ...other next config options
  webpack(config, context) {
    if (!context.isServer && context.dev) {
      config.plugins.push(new I18NextHMRPlugin({ localesDir }))
    }

    return config
  },
}
```

3. Update the **next-i18next.config.js** like so:

```js
const HttpBackend = require('i18next-http-backend/cjs');

const config = {
  i18n: {
    defaultLocale: 'fa',
    locales: ['en', 'fa'],
    localeDetection: false,
  },
  localePath: './public/locales',
  use: typeof window !== 'undefined' ? [HttpBackend] : [],
};

module.exports = config;
```

4. Create a hook for applying the HMR code during development. I created mine in hooks/use-hmr.ts and it looks like this:

```tsx
import { useTranslation } from "next-i18next"
import { useEffect } from "react"

export const useHMR = (): void => {
  const { i18n } = useTranslation()

  if (process.env.NODE_ENV === "development" && !process.browser) {
    import("i18next-hmr/server").then(({ applyServerHMR }) => {
      applyServerHMR(i18n)
    })
  }

  useEffect(() => {
    if (process.env.NODE_ENV === "development") {
      import("i18next-hmr/client").then(({ applyClientHMR }) => {
        applyClientHMR(i18n)
      })
    }
  }, [i18n])
}
```

5. Import and pass **next-i18next.config.js** to **appWithTranslation** (typically in pages/_app.tsx) and use the HMR hook created above within the body of the App component:

```tsx
import { AppProps } from "next/app"
import { FunctionComponent } from "react"
import { appWithTranslation } from "next-i18next"
import { useHMR } from "../hooks/use-hmr"
import i18nextConfig from "../../next-i18next.config"

export const App: FunctionComponent<AppProps> = ({ Component, pageProps }) => {
  useHMR()

  return <Component {...pageProps} />
}

export default appWithTranslation(App, i18nextConfig) // Required to use the HttpBackend that enables HMR on the client
```
6. Create a SSG page (here **faq**):

```tsx
import { GetStaticProps } from 'next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

const Faq = () => {
  return (
    // Content of page
    <></>
  );
};

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  return {
    props: { ...(await serverSideTranslations(locale, ['common', 'faq', 'footer'])) },
  };
};

export default Faq;
```

7. Update content of **faq.json** (any language)
8. Update content of **common.json** (any language)

**Expected behavior**
- faq.json updates **don't** apply to client-side.
- **But** Update of common.json, affecting client-side as well.

I am using:
 - OS: Win
 - i18next-hmr version: 1.7.7
 - next-i18next version: 11.0.0
 - i18next-http-backend version: 1.4.0

It seems Client-HMR only works in case that **all** namespaces declared in next-i18next-config, because the plugin check for **i18n.options.ns** by default.

**Comment by skmohammadi** [comment] 2022-05-23 13:27
If we change the source code of **client-hmr.js** as below, problem will be solved:

```js
    // other code

    module.hot.accept('./trigger.js', () => {
      const { changedFiles } = require('./trigger.js');
      const currentNSList = Object.keys(i18n.store.data[i18n.language]); // get all loaded namespaces

      const list = changedFiles
        .map((changedFile) => extractLangAndNS(changedFile, currentNSList))
        .filter(({ lang, ns }) => Boolean(lang) && Boolean(ns));

      if (!list.length) {
        return;
      }

      log(`Got an update with ${printList(list)}`);

      return reloadTranslations(list);
    });

```
#108

**Comment by felixmosh** [comment] 2022-05-24 07:09
As I've suspected, it is an issue in `next-i18next` which is not passing the namespaces to the client, so the data contains some namespace, but not the list.

On the server side it works since the `options.ns` is correct.

### server side
![image](https://user-images.githubusercontent.com/9304194/169969442-510015d6-c290-4bac-ad44-b14918bdcfe5.png)

### client side
![image](https://user-images.githubusercontent.com/9304194/169970118-4947d352-3aab-42e7-9e1d-4a2afd954ef2.png)
![image](https://user-images.githubusercontent.com/9304194/169970135-115312a8-cd70-477f-a94a-c5c681ad656e.png)

Let's open a bug in `next-i8next`

**Comment by felixmosh** [comment] 2022-05-24 07:38
I've opened a [new issue](https://github.com/isaachinman/next-i18next/issues/1839) on `next-i18next`

**Comment by skmohammadi** [comment] 2022-05-28 05:39
**i18next** configuration may contain only default namespace **common**, so `options.ns` will be equal to `['common']`; on both the server and client sides.

**Comment by felixmosh** [comment] 2022-05-28 05:41
It is not true, in the images I've added, the values are from server & client at runtime

**Comment by skmohammadi** [comment] 2022-05-28 05:56
@felixmosh  You are right.
And what do you think about `i18n.store.data`? It includes all namespaces on both sides.

**Comment by felixmosh** [comment] 2022-05-28 06:48
It's possible, but I don't want to solve a bug of other lib.

**Comment by felixmosh** [comment] 2022-05-29 08:17
@skmohammadi if you have sometime, maybe you can prepare a PR for `next-i18next`, it should be straight forward.

**Comment by skmohammadi** [comment] 2022-05-29 10:20
> It's possible, but I don't want to solve a bug of other lib.

It appears to be a problem with your library and implementation of *i18n.store.data* will correct it.

**Comment by felixmosh** [comment] 2022-05-29 10:35
How i18n.options related to this lib, this lib is only reading from it.
The problem is that the field is not properly passed to the client (as a proof, server side works properly).

**Comment by felixmosh** [comment] 2022-07-17 08:15
Hi @skmohammadi , can you try `v11.2.1` it should work now.
Check https://github.com/isaachinman/next-i18next/issues/1839

**Comment by skmohammadi** [comment] 2022-07-19 04:53
Hi @felixmosh. I appreciate you following up on this matter. Sure, I'll check it out.

**Comment by skmohammadi** [comment] 2022-07-19 05:09
Thank you @felixmosh. Now, it works as expected.

**Comment by felixmosh** [comment] 2022-07-19 05:51
Can we close this issue?

**Closed** 2022-07-19 11:34 UTC

**Comment by felixmosh** [comment] 2022-07-19 16:19
Did you managed to add http-backend for the client side?
For some reason, I'm not seen where this `backend` passed to the instance on **client side** :|

**Comment by felixmosh** [comment] 2022-07-19 19:25
Please check the new example of Next-i18next https://github.com/felixmosh/i18next-hmr/tree/master/examples/next-with-next-i18next-v11
